### PR TITLE
Typescript Support

### PR DESCRIPTION
**Pull request by HadesArchitect**
Added typescript, eslint, etc.

To test:
- review the changeset
- checkout branch `eslint`
- `docker run -v ${PWD}:/opt/gcds -w /opt/gcds node npm install`
- `docker run -v ${PWD}:/opt/gcds -w /opt/gcds node node_modules/eslint/bin/eslint.js src/*.js`

Expected output:
image

### CODE REVIEW

**Comment by HadesArchitect** [comment]
`docker run -v ${PWD}:/opt/gcds -w /opt/gcds node node_modules/grunt-cli/bin/grunt`

**Comment by DevAleks** [comment]
Review ok!

**Comment by DevAleks** [comment]
Test fail:
scr1

**Comment by HadesArchitect** [comment]
@DevAleks It's the mistake in how-to-test, a missing step. Fixed it, repeat, please.

**Comment by DevAleks** [comment]
@HadesArchitect, I'v just included this step in testing, placed hello-cassandra.js in src/ and run it. But result still looks strangre:
scr2

**Comment by HadesArchitect** [comment]
@DevAleks I'd guess it tries to apply strict typescript rules to the plain JS file, not really sure... At least for me it works well. 
image

**Comment by DevAleks** [comment]
@HadesArchitect, I tested it with `.tc` and its worked correctly. Test passed :)

**Pull request merged**
